name: angular_reuable_workflow
on:
  workflow_dispatch:

jobs:
  call-code-scanning:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses:  GitActions-POC/Code-Scanning-Repo/.github/workflows/Codacy-security-scan.yml@main
    with:
      output: results.sarif
      format: sarif
      code-quality-check: yes
  call-common-template:
    needs: call-code-scanning
    if: |
      always() &&
      (needs.call-code-scanning.result == 'skipped' || needs.call-code-scanning.result == 'success')
    permissions: 
      contents: write
      issues: read
      checks: write
      pull-requests: write
    uses:  GitActions-POC/Code-Scanning-Repo/.github/workflows/angular-common-template.yml@main
    with:
      NodeJS-version: 16
      environment: prod
      publish_dir: dist/Angular-Code-Scanning
      enable_jekyll: true
